"""empty message

Revision ID: abc401876132
Revises: 
Create Date: 2025-02-27 20:09:39.652332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc401876132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lights', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('cur_response', sa.String(length=1000), nullable=True),
    sa.Column('prev_response', sa.String(length=1000), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approval_date', sa.String(length=100), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('current_month', sa.Integer(), nullable=True),
    sa.Column('last_month', sa.Integer(), nullable=True),
    sa.Column('two_months_ago', sa.Integer(), nullable=True),
    sa.Column('three_months_ago', sa.Integer(), nullable=True),
    sa.Column('one_year_ago', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insights')
    # ### end Alembic commands ###
